name: build ts into js
on:
  push:
  pull_request:

jobs:
  deploy:
    permissions:
      contents: write
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        token: ${{ secrets.PAT }}
    - name: install node v18
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: yarn install
      run: yarn install
    - name: ts compile
      run: yarn build
    - name: git workflow copy
      run: cp .github/
    - name: Push
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: deploy
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.PAT }}
        MESSAGE: "Build: ({sha}) {msg}"